name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Backend
      run: |
        cd backend
        docker build -t gmail-saas-backend:test .
    
    - name: Build Frontend  
      run: |
        cd frontend
        docker build -t gmail-saas-frontend:test .
    
    - name: Test Docker Compose
      run: |
        cp .env.example .env
        docker-compose config
    
    - name: Success
      run: echo "✅ Build successful!"

